### ISSUE TITLE
TWiT error loading Add on

### ISSUE THREAD

**Issue by armandoruas** [divingmule/plugin.video.twit#10]
Hello.
I'm getting this error
![kodi_error](https://cloud.githubusercontent.com/assets/19244261/15094929/f65f9d92-14aa-11e6-8cb6-8bc185c5a262.jpg)
Can someone help!
Here are the logs:
23:22:31 T:16576   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "C:\Users\Armando Ruas\AppData\Roaming\Kodi\addons\plugin.video.twit\default.py", line 444, in <module>
                                                display_main()
                                              File "C:\Users\Armando Ruas\AppData\Roaming\Kodi\addons\plugin.video.twit\default.py", line 100, in display_main
                                                display_shows('active')
                                              File "C:\Users\Armando Ruas\AppData\Roaming\Kodi\addons\plugin.video.twit\default.py", line 78, in display_shows
                                                shows = cache.cacheFunction(shows_cache)
                                              File "C:\Users\Armando Ruas\AppData\Roaming\Kodi\addons\script.common.plugin.cache\lib\StorageServer.py", line 570, in cacheFunction
                                                ret_val = funct(_args)
                                              File "C:\Users\Armando Ruas\AppData\Roaming\Kodi\addons\plugin.video.twit\default.py", line 69, in shows_cache
                                                'active': parse_shows_to_list(base_url + '/shows?shows_active=1'),
                                              File "C:\Users\Armando Ruas\AppData\Roaming\Kodi\addons\plugin.video.twit\default.py", line 59, in parse_shows_to_list
                                                convertEntities=BeautifulSoup.HTML_ENTITIES)
                                              File "C:\Users\Armando Ruas\AppData\Roaming\Kodi\addons\script.module.beautifulsoup\lib\BeautifulSoup.py", line 1522, in **init**
                                                BeautifulStoneSoup.**init**(self, *args, *_kwargs)
                                              File "C:\Users\Armando Ruas\AppData\Roaming\Kodi\addons\script.module.beautifulsoup\lib\BeautifulSoup.py", line 1147, in **init**
                                                self._feed(isHTML=isHTML)
                                              File "C:\Users\Armando Ruas\AppData\Roaming\Kodi\addons\script.module.beautifulsoup\lib\BeautifulSoup.py", line 1171, in _feed
                                                smartQuotesTo=self.smartQuotesTo, isHTML=isHTML)
                                              File "C:\Users\Armando Ruas\AppData\Roaming\Kodi\addons\script.module.beautifulsoup\lib\BeautifulSoup.py", line 1773, in __init__
                                                self._detectEncoding(markup, isHTML)
                                              File "C:\Users\Armando Ruas\AppData\Roaming\Kodi\addons\script.module.beautifulsoup\lib\BeautifulSoup.py", line 1918, in _detectEncoding
                                                '^<\?._encoding=[\'"](.*?)[\'"]._\?>').match(xml_data)
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--
23:22:31 T:15316   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.twit/?content_type=video
23:22:31 T:15316   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twit/?content_type=video) failed
Thank you.
ArmandoRuas

**Comment by divingmule** [comment]
Hi, there seems to be a bug in Python 2 with the SSL that TWiT is using. As a workaround I've updated the addon to use hard coded show info and RSS feeds.

At the moment you can try it out by using the install from zip file option > https://github.com/divingmule/plugin.video.twit/releases/download/v2.1.4/plugin.video.twit-2.1.4.zip
