### ISSUE TITLE
All TWiT.tv Shows error

### ISSUE THREAD

**Issue by ghost** [divingmule/plugin.video.twit#12]
Has been working great for 12 months, but started getting an error message a few days ago when I select All TWiT.tv Shows, and it won't load any more.  Other shows work fine.
Below is the Python exception from the log:

12:26:08 T:4276  NOTICE: [plugin.video.twit-2.1.5]: Mode: rss_feed, Name: All TWiT.tv Shows, URL: /shows/all-twittv-shows
12:26:08 T:632  NOTICE: script.tv.show.next.aired: ### no prior data found
12:26:10 T:4276   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Media-user\AppData\Roaming\Kodi\addons\plugin.video.twit\default.py", line 289, in <module>
                                                get_rss_feed(params['url'], params['name'], params['iconimage'])
                                              File "C:\Users\Media-user\AppData\Roaming\Kodi\addons\plugin.video.twit\default.py", line 93, in get_rss_feed
                                                info['duration'] = duration_to_seconds(i['itunes_duration'])
                                              File "C:\Users\Media-user\AppData\Roaming\Kodi\addons\plugin.video.twit\default.py", line 102, in duration_to_seconds
                                                seconds = (((int(d[0]) \* 60) + int(d[1])) \* 60) + int(d[2])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
12:26:10 T:3828   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.twit/?content_type=video&iconimage=http%3a%2f%2ftwit.cachefly.net%2fcoverart%2fall%2fall1400.jpg&mode=rss_feed&name=All%20TWiT.tv%20Shows&url=%2fshows%2fall-twittv-shows

Any ideas?

**Comment by ghost** [comment]
Fix detailed here :http://forum.kodi.tv/showthread.php?tid=183336&page=12
Source has been updated.
