### ISSUE TITLE
[Security Now]  Fails to load ...

### ISSUE THREAD

**Issue by rprimus** [divingmule/plugin.video.twit#5]
Sat Dec  5 20:04:23 GMT 2015

Kodi version: 15.2 (Compiled Oct 19 2015)
Plugin version: 2.1.1)

Also failing for `iOS Today` and  `Coding 101`

The only thing I can see in common, is that the titles contain `','`.
.
The default URI is now `https`.

From `kodi.log`:

```
04:28:12 T:1696844576  NOTICE: -->Python Interpreter Initialized<--
04:28:12 T:1513337712   ERROR: Control 515 in window 10025 has been asked to focus, but it can't
04:28:13 T:1696844576   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get_text'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.twit/default.py", line 383, in <module>
                                                get_episodes(params['url'], params['iconimage'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.twit/default.py", line 106, in get_episodes
                                                title = i.span.get_text(' ', strip=True)
                                            AttributeError: 'NoneType' object has no attribute 'get_text'
                                            -->End of Python script error report<--
04:28:14 T:1513337712   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.twit/?             content_type=video&iconimage=http%3a%2f%2ftwit.cachefly.net%2fcoverart%2fsn%2fsn1400.jpg&mode=episodes&name=Security%20Now&url=%2fshows%2fsecurity-now
04:28:14 T:1513337712   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twit/?content_type=video&iconimage=http%3a%2f%2ftwit.cachefly.net%2fcoverart%2fsn%2fsn1400.                           jpg&mode=episodes&name=Security%20Now&url=%2fshows%2fsecurity-now) failed
04:28:14 T:1674359120  NOTICE: Thread BackgroundLoader start, auto delete: false
```

This has been happening about 2 weeks now.

**Comment by rprimus** [comment]
Sun Dec  6 15:00:09 GMT 2015

Hi.
Have tracked it down to a bad title (for `Episode 533`) containing unescaped quotes:

``` html
title="A variant of the ransomware "Power Worm" can not be decrypted even after the ransom is paid."
```

For `Coding 101` (Ep 94):

``` html
title="Gig Economy, aka "freelancing", "outsourcing", "seasonal", etc."
```

For iOS Today, the plugin is only seeing:

``` html
15:10:40 T:1689877064   DEBUG: [plugin.video.twit-2.1.1]: <!DOCTYPE doctype html>
                                            <html>
                                             <head>
                                              <meta charset="utf-8">
                                               <script type="text/javascript">
                                                window.NREUM||(NREUM={});NREUM.info = {"agent":"js-agent.newrelic.com/nr-768.min.js","beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseK
                                               </script>
                                               <meta content="IE=edge" http-equiv="X-UA-Compatible">
                                                <title>
                                                 iOS Today | TWiT
                                                </title>
                                                <meta content="width=device-width, initial-scale=1" name="viewport">
                                                 <meta content="IE=Edge" http-equiv="X-UA-Compatible">
                                                  <link href="https://twit.tv/shows/ios-today" rel="canonical"/>
                                                 </meta>
                                                </meta>
                                               </meta>
                                              </meta>
                                             </head>
                                            </html>
```

... containing no episodes.

This is due to more unescaped quotes - this time in a meta tag:

``` html
<meta name="description" content="Leo Laporte and Megan Morrone love their iPhones, iPads, and Apple Watches so much they've created "iOS Today," the TWiT network's first show highlighting the best apps, most helpf…"
```

Twas a fun (first time) experience looking at python code and debugging.

It would be good if only the offending 'episode' were highlighted (as having a problem) and not have the plugin crash.

**Comment by divingmule** [comment]
Thanks @rprimus for letting me know. I should have some time in the next few days to dig into it.

**Comment by divingmule** [comment]
Sorry for the delay, I think this release should resolve the issue.
https://github.com/divingmule/plugin.video.twit/releases/tag/2.1.2

**Comment by rprimus** [comment]
Tue Mar 22 00:33:51 GMT 2016

Thank you @divingmule - all good (`v2.1.3`)!
Keep up the good work!
