### ISSUE TITLE
Error loading plugin:  script failed

### ISSUE THREAD

**Issue by solbu** [divingmule/plugin.video.twit#7]
Sometime in the last few days an error appears uppon loading the TWiT plugin. It seems to crash.
Here is the log entry:

23:18:15 T:140026135267072  NOTICE: -->Python Interpreter Initialized<--
23:18:15 T:140027914086336   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
23:18:16 T:140026135267072   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "/home/solbu/.kodi/addons/plugin.video.twit/default.py", line 444, in <module>
                                                display_main()
                                              File "/home/solbu/.kodi/addons/plugin.video.twit/default.py", line 100, in display_main
                                                display_shows('active')
                                              File "/home/solbu/.kodi/addons/plugin.video.twit/default.py", line 78, in display_shows
                                                shows = cache.cacheFunction(shows_cache)
                                              File "/home/solbu/.kodi/addons/script.common.plugin.cache/lib/StorageServer.py", line 570, in cacheFunction
                                                ret_val = funct(_args)
                                              File "/home/solbu/.kodi/addons/plugin.video.twit/default.py", line 69, in shows_cache
                                                'active': parse_shows_to_list(base_url + '/shows?shows_active=1'),
                                              File "/home/solbu/.kodi/addons/plugin.video.twit/default.py", line 59, in parse_shows_to_list
                                                convertEntities=BeautifulSoup.HTML_ENTITIES)
                                              File "/home/solbu/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 1522, in **init**
                                                BeautifulStoneSoup.**init**(self, *args, *_kwargs)
                                              File "/home/solbu/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 1147, in **init**
                                                self._feed(isHTML=isHTML)
                                              File "/home/solbu/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 1171, in _feed
                                                smartQuotesTo=self.smartQuotesTo, isHTML=isHTML)
                                              File "/home/solbu/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 1773, in __init__
                                                self._detectEncoding(markup, isHTML)
                                              File "/home/solbu/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 1918, in _detectEncoding
                                                '^<\?._encoding=[\'"](.*?)[\'"]._\?>').match(xml_data)
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--
23:18:16 T:140027914086336   ERROR: GetDirectory - Error getting plugin://plugin.video.twit/?content_type=video
23:18:16 T:140027914086336   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twit/?content_type=video) failed

Running Python 2.7.9 on Mageia 5, using latest Kodi packaged for Mageia, version 14.0.
TWiT plugin version: 2.1.3

**Comment by divingmule** [comment]
Hi, the website and the API both seem to be offline. kinda figures this happens just after releasing an add-on update.

**Comment by solbu** [comment]
Ahh. That might indeed be a problem. ;-)
I can't get to the site either.

May I then suggest that in a future version the on-screen error message state that it can't contact the site if it is unavailable for some reason.

And, the plugin is wery nice. Good job.
